title: Your awesome title
author: GitHub User
email: ejalaa12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a website for learning GitHub Pages
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
